const mongoose = require("mongoose");

const airbnbSchema = mongoose.Schema({
  listing_url: String,
  name: String,
  summary: String,
  space: String,
  description: String,
  neighborhood_overview: String,
  notes: String,
  transit: String,
  access: String,
  interaction: String,
  house_rules: String,
  property_type: String,
  room_type: String,
  bed_type: String,
  minimum_nights: String,
  maximum_nights: String,
  last_scraped: Date,
  calendar_last_scraped: Date,
  first_review: Date,
  last_review: Date,
  accommodates: Number,
  bedrooms: Number,
  beds: Number,
  number_of_reviews: Number,
  bathrooms: Number,
  amenities: [String],
  price: Number,
  security_deposit: Number,
  cleaning_fee: Number,
  extra_people: Number,
  guests_included: Number,
  images: mongoose.Schema.Types.Mixed,
  host: mongoose.Schema.Types.Mixed,
  address: mongoose.Schema.Types.Mixed,
  availability: mongoose.Schema.Types.Mixed,
  review_scores: mongoose.Schema.Types.Mixed,
  reviews: [mongoose.Schema.Types.Mixed],
});
const airbnbModel = mongoose.model("listingAndReview", airbnbSchema);
